name: Inkeep Agent

on:
    issue_comment:
        types: [created]
    
    pull_request_review_comment:
        types: [created]
    
    pull_request_review:
        types: [submitted]

    pull_request:
        types: [closed]

permissions:
    contents: read
    pull-requests: read
    id-token: write

jobs:
    trigger-agent:
        if: |
            !contains(github.actor, '[bot]') &&
            (
              (github.event_name == 'pull_request' && github.event.pull_request.merged == true) ||
              (github.event_name == 'issue_comment' && github.event.issue.pull_request && contains(github.event.comment.body, '@inkeep')) ||
              (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@inkeep')) ||
              (github.event_name == 'pull_request_review' && contains(github.event.review.body || '', '@inkeep'))
            )
        runs-on: ubuntu-latest
        steps:
            - name: Trigger Inkeep Agent
              uses: inkeep/inkeep-agents-action@f2ccac1f117a171cac1e9e65852e2196769f50b5 # v0
              with:
                  trigger-url: https://inkeep-agents.ngrok.io/run/tenants/default/projects/test/agents/test/triggers/fevb1vic79k8i7zrcq4e5